// NormalNimDFAParams.h

#ifndef NORMALNIM_DFA_PARAMS_H
#define NORMALNIM_DFA_PARAMS_H

#define NORMALNIM1_SHAPE_PACK 16
#define NORMALNIM1_DFA_PARAMS 1, NORMALNIM1_SHAPE_PACK

#define NORMALNIM2_SHAPE_PACK 16, 16
#define NORMALNIM2_DFA_PARAMS 2, NORMALNIM2_SHAPE_PACK

#define NORMALNIM3_SHAPE_PACK 16, 16, 16
#define NORMALNIM3_DFA_PARAMS 3, NORMALNIM3_SHAPE_PACK

#define NORMALNIM4_SHAPE_PACK 16, 16, 16, 16
#define NORMALNIM4_DFA_PARAMS 4, NORMALNIM4_SHAPE_PACK

#endif
