// NormalNimDFAParams.h

#ifndef NORMALNIM_DFA_PARAMS_H
#define NORMALNIM_DFA_PARAMS_H

#define NORMALNIM1_DFA_SHAPE 16
#define NORMALNIM2_DFA_SHAPE 16, 16
#define NORMALNIM3_DFA_SHAPE 16, 16, 16
#define NORMALNIM4_DFA_SHAPE 16, 16, 16, 16

#endif
