// TicTacToeDFAParams.h

#ifndef TICTACTOE_DFA_PARAMS_H
#define TICTACTOE_DFA_PARAMS_H

#define TICTACTOE2_SHAPE_PACK 3, 3, 3, 3
#define TICTACTOE2_DFA_PARAMS 4, TICTACTOE2_SHAPE_PACK

#define TICTACTOE3_SHAPE_PACK 3, 3, 3, 3, 3, 3, 3, 3, 3
#define TICTACTOE3_DFA_PARAMS 9, TICTACTOE3_SHAPE_PACK

#define TICTACTOE4_SHAPE_PACK 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
#define TICTACTOE4_DFA_PARAMS 16, TICTACTOE4_SHAPE_PACK

#endif
